export const CODES = {
  DUPLICATE_NODE_ID: "duplicate_node_id",
  UNKNOWN_NODE_TYPE: "unknown_node_type",
  MISSING_REQUIRED_PARAMETER: "missing_required_parameter",
  PARAMETER_TYPE_MISMATCH: "parameter_type_mismatch",
  INVALID_FREQUENCY: "invalid_frequency",
  FREQUENCY_FOR_MISSING_NODE: "frequency_for_missing_node",
  DUPLICATE_EDGE_ID: "duplicate_edge_id",
  MISSING_SOURCE_NODE: "missing_source_node",
  MISSING_TARGET_NODE: "missing_target_node",
  INVALID_SOURCE_PORT: "invalid_source_port",
  INVALID_TARGET_PORT: "invalid_target_port",
  PORT_TYPE_MISMATCH: "port_type_mismatch",
  SELF_LOOP: "self_loop",
  CYCLE: "cycle",
  ISOLATED_NODE: "isolated_node",
  UNCONNECTED_INPUT: "unconnected_input",
  RESERVED_NODE_TYPE: "reserved_node_type",
  SUBGRAPH_INVALID_PARAMETERS: "subgraph_invalid_parameters",
  PSEUDO_NODE_INVALID_PARAMETERS: "pseudo_node_invalid_parameters",
  PSEUDO_NODE_AT_ROOT: "pseudo_node_at_root",
  PSEUDO_NODE_DUPLICATE_NAME: "pseudo_node_duplicate_name",
  SUBGRAPH_PORT_UNBOUND: "subgraph_port_unbound",
  SUBGRAPH_PORT_TYPE_MISMATCH: "subgraph_port_type_mismatch",
  SUBGRAPH_INPUT_UNCONNECTED: "subgraph_input_unconnected",
  SUBGRAPH_OUTPUT_UNCONNECTED: "subgraph_output_unconnected",
  EMPTY_SUBGRAPH: "empty_subgraph",
} as const;

export type DiagnosticCode = (typeof CODES)[keyof typeof CODES];
